--proc_delete_time
CREATE OR REPLACE PROCEDURE PR_DELETE_TIME IS
  RECORD_COUNT NUMBER(10);
  CURR_TIME    DATE;
  MAX_TRADTIME DATE;
BEGIN
  CURR_TIME := SYSDATE - 5 / 1440;
  SELECT COUNT(*)
    INTO RECORD_COUNT
    FROM ESBFLOWLOG_TIME
   WHERE OPERSTAMP < CURR_TIME;
  IF RECORD_COUNT > 0 THEN
    SELECT MAX(OPERSTAMP)
      INTO MAX_TRADTIME
      FROM ESBFLOWLOG_TIME
     WHERE OPERSTAMP < CURR_TIME;
    DELETE FROM ESBFLOWLOG_TIME WHERE OPERSTAMP < MAX_TRADTIME - 5 / 1440;
  END IF;
END PR_DELETE_TIME;
/