CREATE OR REPLACE PROCEDURE P_ADD_GNMK(
    AC_FULL    VARCHAR2,--全路径名称
    AC_GNMK    CHAR,--模块代码
    AC_HZMC    VARCHAR2,--汉字名称
    AC_LJMC    VARCHAR2,--路径名称
    AC_YWHJ    CHAR,--业务环节代码
    AC_MKLX_DM    VARCHAR2 default '05', --模块类型代码
    AC_SYSTEMNAME    VARCHAR2 default '系统管理' --业务系统名称
)IS
    LC_FJD_DM  VARCHAR2(30);
    LC_JD_DM   VARCHAR2(30);
    LN_ROW     NUMBER(10);
BEGIN
    IF AC_GNMK='FFFFFFFFFFF' THEN--增加目录
        RAISE_APPLICATION_ERROR(-20000,'增加目录请调用P_ADD_ML');
    END IF;
    
    --开始插入数据
    BEGIN
        insert into QX_GNMK (GNMK_DM, GNMK_HZMC, GNMK_LJMC, MKLX_DM, YWHJ_DM, SYSTEMNAME, CYBJ, CFDK)
        values (AC_GNMK, AC_HZMC, AC_LJMC, AC_MKLX_DM, AC_YWHJ, AC_SYSTEMNAME, 'N','N');--常用标记为N
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20000,'GNMK_DM='||AC_GNMK||' ? '||SQLERRM);
    END;

    IF AC_FULL IS NOT NULL THEN--AC_FULL为空，表示不在树上显示
        --通过目录名称查找父节点代码
        LC_FJD_DM:=P_GET_JD_DM(AC_FULL,'0');
        --获取新节点代码
        LC_JD_DM:=P_GET_JD_NEW(LC_FJD_DM,AC_HZMC,'0');
 --       LN_ROW:=SUBSTR(LC_JD_DM,LENGTH(LC_JD_DM)-2,3);
        SELECT MAX(JD_ORDER) INTO LN_ROW FROM QX_GNMK_TREE WHERE FJD_DM=LC_FJD_DM;
        IF LN_ROW IS NULL THEN
            LN_ROW:=1;
        ELSIF LN_ROW>=999 THEN
            RAISE_APPLICATION_ERROR(-20000,'下属节点超过999，无法扩展！');
        ELSE
            LN_ROW:=LN_ROW+1;
        END IF;
        insert into QX_GNMK_TREE(JD_DM,FJD_DM,JD_MC,GNMK_DM,JDLX_DM,JD_ORDER)
        VALUES (LC_JD_DM,LC_FJD_DM,AC_HZMC, AC_GNMK,'02',LN_ROW);

        --通过目录名称查找父节点代码
        LC_FJD_DM:=P_GET_JD_DM(AC_FULL,'1');
        --获取新节点代码
        LC_JD_DM:=P_GET_JD_NEW(LC_FJD_DM,AC_HZMC,'1');
        SELECT MAX(JD_ORDER) INTO LN_ROW FROM QX_GNMB_GNMK WHERE FJD_DM=LC_FJD_DM AND GNMB_DM='00000000001';
        IF LN_ROW IS NULL THEN
            LN_ROW:=1;
        ELSIF LN_ROW>=999 THEN
            RAISE_APPLICATION_ERROR(-20000,'下属节点超过999，无法扩展！');
        ELSE
            LN_ROW:=LN_ROW+1;
        END IF;
--        LN_ROW:=SUBSTR(LC_JD_DM,LENGTH(LC_JD_DM)-2,3);
        INSERT INTO QX_GNMB_GNMK(GNMB_DM,JD_DM,FJD_DM,JD_MC,GNMK_DM,JD_ORDER)
        VALUES ('00000000001',LC_JD_DM,LC_FJD_DM,AC_HZMC,AC_GNMK,LN_ROW);
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE P_ADD_ML(
    AC_FULL    VARCHAR2,--全路径名称 各级间用~隔开
    AC_HZMC    VARCHAR2 --目录名称
)IS
    LC_FJD_DM  VARCHAR2(21);
    LC_JD_DM   VARCHAR2(21);
    LN_ROW     NUMBER(10);
BEGIN
    --通过目录名称查找父节点代码
    LC_FJD_DM:=P_GET_JD_DM(AC_FULL,'0');
    SELECT COUNT(*) INTO LN_ROW FROM QX_GNMK_TREE WHERE FJD_DM=LC_FJD_DM AND JD_MC=AC_HZMC;
    IF LN_ROW=0 THEN
       BEGIN
          --获取新节点代码
          LC_JD_DM:=P_GET_JD_NEW(LC_FJD_DM,AC_HZMC,'0');
          --    LN_ROW:=SUBSTR(LC_JD_DM,LENGTH(LC_JD_DM)-2,3);
          SELECT MAX(JD_ORDER) INTO LN_ROW FROM QX_GNMK_TREE WHERE FJD_DM=LC_FJD_DM;
          IF LN_ROW IS NULL THEN
              LN_ROW:=1;
          ELSIF LN_ROW>=999 THEN
              RAISE_APPLICATION_ERROR(-20000,'下属节点超过999，无法扩展！');
          ELSE
              LN_ROW:=LN_ROW+1;
          END IF;
          insert into QX_GNMK_TREE(JD_DM,FJD_DM,JD_MC,GNMK_DM,JDLX_DM,JD_ORDER)
          VALUES (LC_JD_DM,LC_FJD_DM,AC_HZMC, 'FFFFFFFFFFF','01',LN_ROW);
       END;
    END IF;
    
    

    --通过目录名称查找父节点代码
    LC_FJD_DM:=P_GET_JD_DM(AC_FULL,'1');
    SELECT COUNT(*) INTO LN_ROW FROM QX_GNMB_GNMK WHERE FJD_DM=LC_FJD_DM AND JD_MC=AC_HZMC AND GNMB_DM='00000000001';
    IF LN_ROW=0 THEN
       BEGIN
          --获取新节点代码
          LC_JD_DM:=P_GET_JD_NEW(LC_FJD_DM,AC_HZMC,'1');
          --    LN_ROW:=SUBSTR(LC_JD_DM,LENGTH(LC_JD_DM)-2,3);
          SELECT MAX(JD_ORDER) INTO LN_ROW FROM QX_GNMB_GNMK WHERE FJD_DM=LC_FJD_DM AND GNMB_DM='00000000001';
          IF LN_ROW IS NULL THEN
              LN_ROW:=1;
          ELSIF LN_ROW>=999 THEN
              RAISE_APPLICATION_ERROR(-20000,'下属节点超过999，无法扩展！');
          ELSE
              LN_ROW:=LN_ROW+1;
          END IF;
          INSERT INTO QX_GNMB_GNMK(GNMB_DM,JD_DM,FJD_DM,JD_MC,GNMK_DM,JD_ORDER)
          VALUES ('00000000001',LC_JD_DM,LC_FJD_DM,AC_HZMC,'FFFFFFFFFFF',LN_ROW);
        END;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE P_DEL_GNMK(AC_GNMK VARCHAR2)
IS
BEGIN
    DELETE QX_GNMB_GNMK WHERE GNMK_DM = AC_GNMK;
    DELETE QX_GNMK_TREE WHERE GNMK_DM = AC_GNMK;
    DELETE QX_GNMK WHERE GNMK_DM = AC_GNMK;
END;
/

CREATE OR REPLACE PROCEDURE P_DEL_ML(
    AC_FULL    VARCHAR2,--全路径名称 各级间用~隔开 如：征收监控~申报征收~增值税申报
    AC_HZMC    VARCHAR2 --目录名称
)IS
    LC_JD_DM   VARCHAR2(21);
    LN_ROW     NUMBER(10);
BEGIN
    --通过目录名称查找节点代码
    LC_JD_DM:=P_GET_JD_DM(AC_FULL||'~'||AC_HZMC,'0');
    SELECT COUNT(*) INTO LN_ROW FROM QX_GNMK_TREE WHERE FJD_DM=LC_JD_DM;
    IF LN_ROW>0 THEN
        RAISE_APPLICATION_ERROR(-20000,'功能模块树存在下属节点，无法删除！');
    END IF;
    DELETE QX_GNMK_TREE WHERE JD_DM=LC_JD_DM;

    --同步超级用户树(地税)
    LC_JD_DM:=P_GET_JD_DM(AC_FULL||'~'||AC_HZMC,'1');
    SELECT COUNT(*) INTO LN_ROW FROM QX_GNMK_TREE WHERE FJD_DM=LC_JD_DM;
    IF LN_ROW>0 THEN
        RAISE_APPLICATION_ERROR(-20000,'功能模块树存在下属节点，无法删除！');
    END IF;
    DELETE QX_GNMB_GNMK WHERE GNMB_DM='00000000001' AND JD_DM=LC_JD_DM;
END;
/

CREATE OR REPLACE PROCEDURE P_ADD_ROOT(
    AC_JD_DM    VARCHAR2,
    AC_JD_MC    VARCHAR2,
    AC_JD_ORDER NUMBER default null
)IS
    LN_COUNT NUMBER(10);
    LN_JD_ORDER NUMBER(10);
BEGIN
     IF AC_JD_ORDER is null THEN
        BEGIN
             SELECT MAX(JD_ORDER) INTO LN_JD_ORDER FROM QX_GNMK_TREE WHERE FJD_DM='0';
             IF LN_JD_ORDER IS NULL THEN
                LN_JD_ORDER:=1;
             ELSIF LN_JD_ORDER>=999 THEN
                RAISE_APPLICATION_ERROR(-20000,'根节点超过999，无法扩展！');
             ELSE
                 LN_JD_ORDER:=LN_JD_ORDER+1;
             END IF;
        END;
     ELSE 
        LN_JD_ORDER:=AC_JD_ORDER;
     END IF;

     SELECT COUNT(*) INTO LN_COUNT FROM QX_GNMK_TREE WHERE JD_DM=AC_JD_DM;
     IF LN_COUNT =0 THEN
         insert into QX_GNMK_TREE(JD_DM,FJD_DM,JD_MC,GNMK_DM,JDLX_DM,JD_ORDER)  
         values (AC_JD_DM, '0',AC_JD_MC,'FFFFFFFFFFF', '01', LN_JD_ORDER);
     END IF;
     
     SELECT COUNT(*) INTO LN_COUNT FROM QX_GNMB_GNMK WHERE JD_DM=AC_JD_DM AND GNMB_DM='00000000001';
     IF LN_COUNT =0 THEN
         INSERT INTO QX_GNMB_GNMK(GNMB_DM,GNMK_DM,JD_DM,FJD_DM,JD_MC,JD_ORDER)
         values ('00000000001','FFFFFFFFFFF',AC_JD_DM,'0', AC_JD_MC, LN_JD_ORDER);
     END IF;
     
END;
/

CREATE OR REPLACE PROCEDURE P_DEL_ROOT(
    AC_JD_DM    VARCHAR2
)IS
    LN_COUNT NUMBER(10);
BEGIN
     SELECT COUNT(*) INTO LN_COUNT FROM QX_GNMK_TREE WHERE FJD_DM=AC_JD_DM;
     IF LN_COUNT >0 THEN
        RAISE_APPLICATION_ERROR(-20000,'QX_GNMK_TREE根节点存在下属节点，无法删除！');
     ELSE
        DELETE FROM QX_GNMK_TREE WHERE JD_DM=AC_JD_DM;
     END IF;
     
     SELECT COUNT(*) INTO LN_COUNT FROM QX_GNMB_GNMK WHERE FJD_DM=AC_JD_DM;
     IF LN_COUNT >0 THEN
        RAISE_APPLICATION_ERROR(-20000,'QX_GNMB_GNMK根节点存在下属节点，无法删除！');
     ELSE
        DELETE FROM QX_GNMB_GNMK WHERE JD_DM=AC_JD_DM AND GNMB_DM='00000000001';
     END IF;
     
END;
/