--proc_delete_flowlog
CREATE OR REPLACE PROCEDURE PR_DELETE_FLOWLOG IS
  RECORD_COUNT NUMBER(10);
  CURR_TIME    DATE;
  MAX_TRADTIME DATE;
BEGIN
  CURR_TIME := SYSDATE - 5 / 1440;
  SELECT COUNT(*)
    INTO RECORD_COUNT
    FROM ESBFLOWLOG_LOG
   WHERE LOGSTAMP < CURR_TIME;
  IF RECORD_COUNT > 0 THEN
    SELECT MAX(LOGSTAMP)
      INTO MAX_TRADTIME
      FROM ESBFLOWLOG_LOG
     WHERE LOGSTAMP < CURR_TIME;
    DELETE FROM ESBFLOWLOG_LOG WHERE LOGSTAMP < MAX_TRADTIME - 5 / 1440;
  END IF;

END PR_DELETE_FLOWLOG;
/