
CREATE TABLE QX_FAV_GNMK_TREE
(
  JD_DM     VARCHAR2(21 BYTE)                   NOT NULL,
  FJD_DM    VARCHAR2(21 BYTE)                   NOT NULL,
  JD_MC     VARCHAR2(80 BYTE)                   NOT NULL,
  GNMK_DM   VARCHAR2(256 BYTE)                      NULL,
  JDLX_DM   VARCHAR2(2 BYTE)                        NULL,
  JD_ORDER  NUMBER(5)                           NOT NULL,
  USERID    VARCHAR2(11 BYTE)                   NOT NULL,
  CONSTRAINT PK_QX_FAV_GNMK_TREE
 PRIMARY KEY
 (JD_DM, USERID)
);

COMMENT ON COLUMN QX_FAV_GNMK_TREE.JD_DM IS '功能模块代码';

COMMENT ON COLUMN QX_FAV_GNMK_TREE.FJD_DM IS '节点类型代码';

COMMENT ON COLUMN QX_FAV_GNMK_TREE.JD_MC IS '节点名称';

COMMENT ON COLUMN QX_FAV_GNMK_TREE.GNMK_DM IS '节点代码';

COMMENT ON COLUMN QX_FAV_GNMK_TREE.JDLX_DM IS '父节点代码';

COMMENT ON COLUMN QX_FAV_GNMK_TREE.JD_ORDER IS '节点顺序';

COMMENT ON COLUMN QX_FAV_GNMK_TREE.USERID IS '用户ID';

CREATE TABLE XT_XTCS
(
  CSXH    VARCHAR2(5 BYTE)                      NOT NULL,
  JG_DM   VARCHAR2(15 BYTE)                     NOT NULL,
  CSMC    VARCHAR2(80 BYTE)                     NOT NULL,
  CSNR    VARCHAR2(500 BYTE)                    NOT NULL,
  SYSM    VARCHAR2(200 BYTE)                        NULL,
  XYBZ    CHAR(1 BYTE)                          NOT NULL,
  JZSZBZ  CHAR(1 BYTE)                              NULL,
  CONSTRAINT PK_XT_XTCS
 PRIMARY KEY
 (CSXH, JG_DM)
);

COMMENT ON TABLE XT_XTCS IS '系统参数';

COMMENT ON COLUMN XT_XTCS.CSXH IS '参数序号';

COMMENT ON COLUMN XT_XTCS.JG_DM IS '机构代码';

COMMENT ON COLUMN XT_XTCS.CSMC IS '参数名称';

COMMENT ON COLUMN XT_XTCS.CSNR IS '参数内容';

COMMENT ON COLUMN XT_XTCS.SYSM IS '使用说明';

COMMENT ON COLUMN XT_XTCS.XYBZ IS '选用标志';

COMMENT ON COLUMN XT_XTCS.JZSZBZ IS '集中设置标志';


CREATE TABLE QX_SYSTEM_GW
(
  SYSTEMNAME    VARCHAR2(50 BYTE)               NOT NULL,
  GW_DM         VARCHAR2(15 BYTE)               NOT NULL,
  GW_MC         VARCHAR2(100 BYTE)                  NULL,
  SYSTEM_GW_DM  VARCHAR2(15 BYTE)               NOT NULL,
  SYSTEM_GW_MC  VARCHAR2(100 BYTE)                  NULL,
  CONSTRAINT QX_SYSTEM_GW_PK
 PRIMARY KEY
 (SYSTEMNAME, GW_DM)
);


CREATE TABLE QX_GW_EX
(
  GW_DM     VARCHAR2(15 BYTE)                   NOT NULL,
  QX_JG_DM  VARCHAR2(15 BYTE)                   NOT NULL,
  CONSTRAINT PK_QX_GW_EX
 PRIMARY KEY
 (GW_DM, QX_JG_DM)
);


CREATE TABLE QX_GNMB
(
  GNMB_DM   VARCHAR2(11 BYTE)                   NOT NULL,
  GNMB_MC   VARCHAR2(80 BYTE)                   NOT NULL,
  SS_GW_DM  VARCHAR2(15 BYTE)                       NULL,
  JSSX_DM   VARCHAR2(2 BYTE)                    NOT NULL,
  JG_DM     VARCHAR2(15 BYTE)                   DEFAULT '00000000000'         NOT NULL,
  SFGXJS    CHAR(1 BYTE)                        DEFAULT 'N'                   NOT NULL,
  CONSTRAINT PK_QX_GNMB
 PRIMARY KEY
 (GNMB_DM)
);

COMMENT ON TABLE QX_GNMB IS '功能模(角色)';

COMMENT ON COLUMN QX_GNMB.GNMB_DM IS '功能模板代码';

COMMENT ON COLUMN QX_GNMB.GNMB_MC IS '功能模板名称';

COMMENT ON COLUMN QX_GNMB.SS_GW_DM IS '所属岗位代码';

COMMENT ON COLUMN QX_GNMB.JSSX_DM IS '角色属性';


CREATE TABLE WSQCZCLFS
(
  WSQCZCLFS_DM  VARCHAR2(16 BYTE)               DEFAULT '00'                  NOT NULL,
  WSQCZCLFS_MC  VARCHAR2(256 BYTE)              DEFAULT '未授权操作方式'      NOT NULL,
  YXBZ          CHAR(1 BYTE)                    DEFAULT 'Y'                   NOT NULL,
  XYBZ          CHAR(1 BYTE)                    DEFAULT 'Y'                   NOT NULL,
  CONSTRAINT PK_WSQCZCLFS
 PRIMARY KEY
 (WSQCZCLFS_DM)
);

COMMENT ON TABLE WSQCZCLFS IS '未授权操作处理方式';

COMMENT ON COLUMN WSQCZCLFS.WSQCZCLFS_DM IS '未授权操作处理方式代码';

COMMENT ON COLUMN WSQCZCLFS.WSQCZCLFS_MC IS '未授权操作处理方式名称';

COMMENT ON COLUMN WSQCZCLFS.YXBZ IS '有效标志';

COMMENT ON COLUMN WSQCZCLFS.XYBZ IS '选用标志';


CREATE TABLE QX_JG_GNMK
(
  JG_DM    VARCHAR2(15 BYTE)                    NOT NULL,
  GNMK_DM  VARCHAR2(256 BYTE)                   NOT NULL,
  SDATE    DATE                                 NOT NULL,
  EDATE    DATE                                 NOT NULL,
  CONSTRAINT PK_QX_JG_GNMK
 PRIMARY KEY
 (JG_DM, GNMK_DM)
);



CREATE TABLE QX_FAV_GNMK
(
  USERID   VARCHAR2(11 BYTE)                    NOT NULL,
  GNMK_DM  VARCHAR2(256 BYTE)                   NOT NULL,
  GW_DM    VARCHAR2(15 BYTE)                    NOT NULL,
  JD_MC    VARCHAR2(80 BYTE)                    NOT NULL,
  CONSTRAINT PK_QX_FAV_GNMK
 PRIMARY KEY
 (USERID, GW_DM, GNMK_DM)
);



CREATE TABLE HLP_GNMK
(
  ID         CHAR(40 BYTE)                      NOT NULL,
  CZRY_DATE  DATE                               DEFAULT sysdate               NOT NULL,
  CZRY_MC    VARCHAR2(60 BYTE)                      NULL,
  CZRY_DM    CHAR(11 BYTE)                          NULL,
  KEYWORD    VARCHAR2(2000 BYTE)                    NULL,
  REMARK     VARCHAR2(2000 BYTE)                    NULL,
  GNMK_DM    VARCHAR2(256 BYTE)                     NULL,
  GNMK_HZMC  VARCHAR2(120 BYTE)                     NULL,
  YWHJ_DM    CHAR(6 BYTE)                           NULL,
  CONTENT    VARCHAR2(4000 BYTE)                    NULL,
  PATH       VARCHAR2(256 BYTE)                     NULL,
  PRIMARY KEY
 (ID)
);

COMMENT ON TABLE HLP_GNMK IS '帮助-功能模块操作手册';

COMMENT ON COLUMN HLP_GNMK.CZRY_MC IS '操作人员名称';

COMMENT ON COLUMN HLP_GNMK.CZRY_DM IS '操作人员代码';

COMMENT ON COLUMN HLP_GNMK.KEYWORD IS '操作关键字';

COMMENT ON COLUMN HLP_GNMK.REMARK IS '备注';

COMMENT ON COLUMN HLP_GNMK.GNMK_DM IS '功能模块代码';

COMMENT ON COLUMN HLP_GNMK.GNMK_HZMC IS '功能模块名称';

COMMENT ON COLUMN HLP_GNMK.YWHJ_DM IS '业务环节代码';

COMMENT ON COLUMN HLP_GNMK.CONTENT IS '操作手册内容';

COMMENT ON COLUMN HLP_GNMK.PATH IS '操作手册文件路径';


CREATE TABLE DM_YWHJ
(
  YWHJ_DM  VARCHAR2(6 BYTE)                     NOT NULL,
  YWHJ_MC  VARCHAR2(80 BYTE)                    NOT NULL,
  XYBZ     CHAR(1 BYTE)                         NOT NULL,
  YXBZ     CHAR(1 BYTE)                         NOT NULL,
  CONSTRAINT PK_DM_YWHJ
 PRIMARY KEY
 (YWHJ_DM)
);

COMMENT ON TABLE DM_YWHJ IS '业务环节代码';

COMMENT ON COLUMN DM_YWHJ.YWHJ_DM IS '业务环节代码';

COMMENT ON COLUMN DM_YWHJ.YWHJ_MC IS '业务环节名称';

COMMENT ON COLUMN DM_YWHJ.XYBZ IS '选用标志';

COMMENT ON COLUMN DM_YWHJ.YXBZ IS '有效标志';


CREATE TABLE DM_MKLX
(
  MKLX_DM  VARCHAR2(2 BYTE)                     NOT NULL,
  MKLX_MC  VARCHAR2(20 BYTE)                    NOT NULL,
  XYBZ     CHAR(1 BYTE)                         DEFAULT 'Y'                   NOT NULL,
  YXBZ     CHAR(1 BYTE)                         DEFAULT 'Y'                   NOT NULL,
  CONSTRAINT PK_DM_MKLX
 PRIMARY KEY
 (MKLX_DM)
);

COMMENT ON COLUMN DM_MKLX.MKLX_DM IS '模块类型代码';

COMMENT ON COLUMN DM_MKLX.MKLX_MC IS '模块类型名称';

COMMENT ON COLUMN DM_MKLX.XYBZ IS '选用标志';

COMMENT ON COLUMN DM_MKLX.YXBZ IS '有效标志';


CREATE TABLE QX_SYSTEM_USER
(
  SYSTEMNAME  VARCHAR2(50 BYTE)                 NOT NULL,
  USERID      VARCHAR2(11 BYTE)                 NOT NULL,
  NAME        VARCHAR2(20 BYTE)                     NULL,
  CZRY_MC     VARCHAR2(60 BYTE)                     NULL,
  LOGINNAME   VARCHAR2(40 BYTE)                 NOT NULL,
  PASSWORD    VARCHAR2(40 BYTE)                     NULL,
  CONSTRAINT QX_SYSTEM_USER_PK
 PRIMARY KEY
 (SYSTEMNAME, USERID)
);



CREATE TABLE QX_SYSTEM
(
  SYSTEMNAME         VARCHAR2(80 BYTE)          NOT NULL,
  DESCRIPTION        VARCHAR2(50 BYTE)              NULL,
  ICONURL            VARCHAR2(50 BYTE)              NULL,
  VIRTRULROOTNAME    VARCHAR2(50 BYTE)              NULL,
  COOKIENAME         VARCHAR2(50 BYTE)              NULL,
  REALROOTURL        VARCHAR2(200 BYTE)             NULL,
  WELCOMETITTLE      VARCHAR2(50 BYTE)              NULL,
  WELCOMEURL         VARCHAR2(200 BYTE)             NULL,
  LOGINURL           VARCHAR2(500 BYTE)             NULL,
  LOGINTYPE          VARCHAR2(10 BYTE)          DEFAULT 'U'                   NOT NULL,
  LOGOUTURL          VARCHAR2(200 BYTE)             NULL,
  LOGOUTTYPE         VARCHAR2(10 BYTE)          DEFAULT 'U'                   NOT NULL,
  USERPARAMNAME      VARCHAR2(50 BYTE)              NULL,
  PASSWORDPARAMNAME  VARCHAR2(50 BYTE)              NULL,
  LOGINSUCCESSTAG    VARCHAR2(200 BYTE)         DEFAULT ':CONSOLE:'               NULL,
  TESTURL            VARCHAR2(200 BYTE)             NULL,
  SORTORDER          VARCHAR2(2 BYTE)           DEFAULT '99'                  NOT NULL,
  XYBZ               VARCHAR2(1 BYTE)           DEFAULT 'Y'                   NOT NULL,
  YXBZ               VARCHAR2(1 BYTE)           DEFAULT 'Y'                   NOT NULL,
  BASEURL            VARCHAR2(100 BYTE)         DEFAULT '/ctais'                  NULL,
  LOGINTIME          VARCHAR2(1 BYTE)           DEFAULT 'S'                       NULL,
  SCRIPT             CLOB                           NULL,
  SESSIONKEEP        VARCHAR2(1 BYTE)           DEFAULT 'Y'                       NULL,
  SESSIONKEEPTYPE    VARCHAR2(10 BYTE)          DEFAULT 'U'                       NULL,
  SESSIONKEEPURL     VARCHAR2(500 BYTE)             NULL,
  UNIUSERTYPE        VARCHAR2(10 BYTE)          DEFAULT 'L'                       NULL,
  UNIUSERON          VARCHAR2(1 BYTE)           DEFAULT 'N'                       NULL,
  UNIUSERDATA        VARCHAR2(200 BYTE)             NULL,
  PRIMARY KEY
 (SYSTEMNAME)
);

COMMENT ON TABLE QX_SYSTEM IS '系统';

COMMENT ON COLUMN QX_SYSTEM.SYSTEMNAME IS '系统名称';

COMMENT ON COLUMN QX_SYSTEM.DESCRIPTION IS '系统描述';

COMMENT ON COLUMN QX_SYSTEM.WELCOMETITTLE IS '欢迎标题';

COMMENT ON COLUMN QX_SYSTEM.WELCOMEURL IS '欢迎页url';

COMMENT ON COLUMN QX_SYSTEM.LOGINURL IS '登录地址';

COMMENT ON COLUMN QX_SYSTEM.LOGINTYPE IS '登录类型';

COMMENT ON COLUMN QX_SYSTEM.LOGOUTURL IS '退出地址';

COMMENT ON COLUMN QX_SYSTEM.LOGOUTTYPE IS '退出类型';

COMMENT ON COLUMN QX_SYSTEM.LOGINSUCCESSTAG IS '登录成功标志';

COMMENT ON COLUMN QX_SYSTEM.BASEURL IS '基本路径';

COMMENT ON COLUMN QX_SYSTEM.SCRIPT IS '执行脚本';


CREATE TABLE QX_JG_QXJG
(
  JG_DM     VARCHAR2(15 BYTE)                   NOT NULL,
  QX_JG_DM  VARCHAR2(15 BYTE)                   NOT NULL,
  CONSTRAINT PK_QX_JG_QXJG
 PRIMARY KEY
 (JG_DM)
);



CREATE TABLE DM_JG
(
  JG_DM      VARCHAR2(15 BYTE)                  NOT NULL,
  JG_MC      VARCHAR2(80 BYTE)                  NOT NULL,
  JG_JC      VARCHAR2(50 BYTE)                  NOT NULL,
  JG_BZ      CHAR(1 BYTE)                       NOT NULL,
  SJ_JG_DM   VARCHAR2(15 BYTE)                  NOT NULL,
  DWLSGX_DM  VARCHAR2(2 BYTE)                   NOT NULL,
  JG_JG      VARCHAR2(10 BYTE)                      NULL,
  JGYB       VARCHAR2(6 BYTE)                       NULL,
  JGDZ       VARCHAR2(80 BYTE)                      NULL,
  JGDH       VARCHAR2(30 BYTE)                      NULL,
  CZDH       VARCHAR2(30 BYTE)                      NULL,
  DYDZ       VARCHAR2(50 BYTE)                      NULL,
  XZQH_DM    VARCHAR2(15 BYTE)                      NULL,
  JGFZR_DM   VARCHAR2(11 BYTE)                      NULL,
  JBDM       VARCHAR2(30 BYTE)                  NOT NULL,
  JCDM       CHAR(1 BYTE)                       NOT NULL,
  XYBZ       CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL,
  YXBZ       CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL,
  CONSTRAINT CHK_DM_JG_1
 CHECK ("JG_BZ"='J' OR "JG_BZ"='B' OR "JG_BZ"='Q'),
  CONSTRAINT PK_DM_JG
 PRIMARY KEY
 (JG_DM)
);

COMMENT ON TABLE DM_JG IS '机构';

COMMENT ON COLUMN DM_JG.JG_DM IS '机构代码';

COMMENT ON COLUMN DM_JG.JG_MC IS '机构名称';

COMMENT ON COLUMN DM_JG.JG_JC IS '机构简称';

COMMENT ON COLUMN DM_JG.JG_BZ IS '机构标志';

COMMENT ON COLUMN DM_JG.SJ_JG_DM IS '上级机构代码';

COMMENT ON COLUMN DM_JG.DWLSGX_DM IS '机构级次代码';

COMMENT ON COLUMN DM_JG.JG_JG IS '机构局轨';

COMMENT ON COLUMN DM_JG.JGYB IS '机构邮编';

COMMENT ON COLUMN DM_JG.JGDZ IS '机构地址';

COMMENT ON COLUMN DM_JG.JGDH IS '机构电话';

COMMENT ON COLUMN DM_JG.CZDH IS '传真电话';

COMMENT ON COLUMN DM_JG.DYDZ IS '电邮地址';

COMMENT ON COLUMN DM_JG.XZQH_DM IS '行政区划代码';

COMMENT ON COLUMN DM_JG.JGFZR_DM IS '负责人';

COMMENT ON COLUMN DM_JG.JBDM IS '级别代码';

COMMENT ON COLUMN DM_JG.JCDM IS '级次代码';

COMMENT ON COLUMN DM_JG.XYBZ IS '选用标志';

COMMENT ON COLUMN DM_JG.YXBZ IS '有效标志';


CREATE TABLE DM_XZQH
(
  XZQH_DM     VARCHAR2(15 BYTE)                 NOT NULL,
  XZQH_MC     VARCHAR2(80 BYTE)                     NULL,
  XZQH_JC     VARCHAR2(50 BYTE)                     NULL,
  XZQH_QC     VARCHAR2(512 BYTE)                    NULL,
  JCDM        CHAR(1 BYTE)                          NULL,
  JBDM        VARCHAR2(15 BYTE)                     NULL,
  SJ_XZQH_DM  VARCHAR2(15 BYTE)                     NULL,
  XYBZ        CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL,
  YXBZ        CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL,
  DWLSGX_DM   VARCHAR2(2 BYTE)                      NULL,
  CONSTRAINT PK_DM_XZQH
 PRIMARY KEY
 (XZQH_DM)
);

COMMENT ON TABLE DM_XZQH IS '行政区划代码';

COMMENT ON COLUMN DM_XZQH.XZQH_DM IS '行政区划代码';

COMMENT ON COLUMN DM_XZQH.XZQH_MC IS '行政区划名称';

COMMENT ON COLUMN DM_XZQH.XZQH_JC IS '行政区划简称';

COMMENT ON COLUMN DM_XZQH.XZQH_QC IS '行政区划全称';

COMMENT ON COLUMN DM_XZQH.JCDM IS '级次代码';

COMMENT ON COLUMN DM_XZQH.JBDM IS '级别代码';

COMMENT ON COLUMN DM_XZQH.SJ_XZQH_DM IS '上级行政区划代码';

COMMENT ON COLUMN DM_XZQH.XYBZ IS '选用标志';

COMMENT ON COLUMN DM_XZQH.YXBZ IS '有效标志';

COMMENT ON COLUMN DM_XZQH.DWLSGX_DM IS '单位隶属关系代码';



CREATE TABLE DM_DWLSGX
(
  DWLSGX_DM  VARCHAR2(2 BYTE)                   NOT NULL,
  DWLSGX_MC  VARCHAR2(32 BYTE)                  NOT NULL,
  DWLSGX_SM  VARCHAR2(256 BYTE)                     NULL,
  XYBZ       CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL,
  YXBZ       CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL
);

COMMENT ON TABLE DM_DWLSGX IS '单位隶属关系代码';

COMMENT ON COLUMN DM_DWLSGX.DWLSGX_DM IS '单位隶属关系代码';

COMMENT ON COLUMN DM_DWLSGX.DWLSGX_MC IS '单位隶属关系名称';

COMMENT ON COLUMN DM_DWLSGX.DWLSGX_SM IS '单位隶属关系说明';

COMMENT ON COLUMN DM_DWLSGX.XYBZ IS '选用标志';

COMMENT ON COLUMN DM_DWLSGX.YXBZ IS '有效标志';



CREATE TABLE XT_TEMPTABLECATALOG
(
  TABLENAME           VARCHAR2(255 BYTE)        NOT NULL,
  CREATINGTIME        DATE                      NOT NULL,
  EXPIRINGTIME        DATE                          NULL,
  CONNECTIONPOOLNAME  VARCHAR2(255 BYTE)            NULL,
  CONSTRAINT PK_XT_TEMPTABLECATALOG
 PRIMARY KEY
 (TABLENAME)
);

COMMENT ON TABLE XT_TEMPTABLECATALOG IS '临时表编目录。持久化已申请的临时表信息';

COMMENT ON COLUMN XT_TEMPTABLECATALOG.TABLENAME IS 'TABLENAME';

COMMENT ON COLUMN XT_TEMPTABLECATALOG.CREATINGTIME IS '创建时间';

COMMENT ON COLUMN XT_TEMPTABLECATALOG.EXPIRINGTIME IS '过期时间';

COMMENT ON COLUMN XT_TEMPTABLECATALOG.CONNECTIONPOOLNAME IS '临时表所在数据库的连接池名称，为空表示在生产环境（使用缺省池）。删除临时表时将使用该连接池。';


CREATE TABLE XT_JHLX
(
  XT_JHLX_JHLXNM  VARCHAR2(32 BYTE)             NOT NULL,
  XT_JHLX_ZDLBNM  VARCHAR2(32 BYTE)                 NULL,
  XT_JHLX_JHLXBM  VARCHAR2(32 BYTE)                 NULL,
  XT_JHLX_JC      CHAR(1 BYTE)                      NULL,
  XT_JHLX_LXMC    VARCHAR2(32 BYTE)                 NULL,
  XT_JHLX_SFSXJH  CHAR(1 BYTE)                      NULL,
  XT_JHLX_ZJKCBZ  CHAR(1 BYTE)                      NULL,
  XT_JHLX_DKDBZ   CHAR(1 BYTE)                      NULL,
  XT_JHLX_ZT      CHAR(1 BYTE)                      NULL,
  XT_JHLX_SXH     NUMBER(12)                        NULL,
  XT_JHLX_SFMX    CHAR(1 BYTE)                      NULL,
  XT_JHLX_WHRXM   VARCHAR2(20 BYTE)                 NULL,
  XT_JHLX_WHRNM   VARCHAR2(32 BYTE)                 NULL,
  XT_JHLX_WHSJ    VARCHAR2(15 BYTE)                 NULL,
  XT_JHLX_SFZDCL  CHAR(1 BYTE)                      NULL,
  XT_JHLX_CZBZ    CHAR(1 BYTE)                      NULL,
  XT_JHLX_SFBZ    CHAR(1 BYTE)                      NULL,
  XT_JHLX_CSBZ    VARCHAR2(2 BYTE)                  NULL,
  XT_JHLX_JSDWNM  VARCHAR2(32 BYTE)                 NULL,
  PRIMARY KEY
 (XT_JHLX_JHLXNM)
);



CREATE TABLE XT_GGDMZB
(
  XT_GGDMZB_NM      VARCHAR2(32 BYTE)           NOT NULL,
  XT_GGDMZB_ZDLBNM  VARCHAR2(32 BYTE)               NULL,
  XT_GGDMZB_BM      VARCHAR2(32 BYTE)               NULL,
  XT_GGDMZB_GGDMMC  VARCHAR2(100 BYTE)              NULL,
  XT_GGDMZB_ZJM     VARCHAR2(16 BYTE)               NULL,
  XT_GGDMZB_SXH     NUMBER(12)                      NULL,
  XT_GGDMZB_ZT      CHAR(1 BYTE)                    NULL,
  XT_GGDMZB_JC      CHAR(1 BYTE)                    NULL,
  XT_GGDMZB_SFMX    CHAR(1 BYTE)                    NULL
);



CREATE TABLE XT_BMJG
(
  XT_BMJG_ZDLBNM  VARCHAR2(32 BYTE)             NOT NULL,
  XT_BMJG_ZDLBMC  VARCHAR2(32 BYTE)                 NULL,
  XT_BMJG_BMJG    VARCHAR2(32 BYTE)                 NULL,
  XT_BMJG_SJCD    INTEGER                           NULL,
  XT_BMJG_YLCD    INTEGER                           NULL
);


CREATE TABLE XT_BDDMZB
(
  XT_BDDMZB_NM      VARCHAR2(32 BYTE)           NOT NULL,
  XT_BDDMZB_ZDLBNM  VARCHAR2(32 BYTE)               NULL,
  XT_BDDMZB_BM      VARCHAR2(32 BYTE)               NULL,
  XT_BDDMZB_GGDMMC  VARCHAR2(100 BYTE)              NULL,
  XT_BDDMZB_ZJM     VARCHAR2(16 BYTE)               NULL,
  XT_BDDMZB_SXH     NUMBER(12)                      NULL,
  XT_BDDMZB_ZT      CHAR(1 BYTE)                    NULL,
  XT_BDDMZB_JC      CHAR(1 BYTE)                    NULL,
  XT_BDDMZB_SFMX    CHAR(1 BYTE)                    NULL,
  CONSTRAINT PK_XT_BDDMZB
 PRIMARY KEY
 (XT_BDDMZB_NM)
);

COMMENT ON COLUMN XT_BDDMZB.XT_BDDMZB_ZDLBNM IS '引用编码结构表内码';

COMMENT ON COLUMN XT_BDDMZB.XT_BDDMZB_ZT IS '0:否，1：是';

COMMENT ON COLUMN XT_BDDMZB.XT_BDDMZB_SFMX IS '0:否，1：是';



CREATE TABLE XT_BDBMJG
(
  XT_BDBMJG_ZDLBNM  VARCHAR2(32 BYTE)           NOT NULL,
  XT_BDBMJG_ZDLBMC  VARCHAR2(32 BYTE)               NULL,
  XT_BDBMJG_BMJG    VARCHAR2(32 BYTE)               NULL,
  XT_BDBMJG_SJCD    INTEGER                         NULL,
  XT_BDBMJG_YLCD    INTEGER                         NULL,
  CONSTRAINT PK_XT_BDBMJG
 PRIMARY KEY
 (XT_BDBMJG_ZDLBNM)
);



CREATE TABLE XT_BBKZB
(
  XT_BBKZB_BBKZNM   NUMBER(8)                   NOT NULL,
  XT_BBKZB_CPMC     VARCHAR2(60 BYTE)               NULL,
  XT_BBKZB_BBLX     INTEGER                         NULL,
  XT_BBKZB_BBH      VARCHAR2(60 BYTE)               NULL,
  XT_BBKZB_GXSJ     DATE                            NULL,
  XT_BBKZB_BDBH     VARCHAR2(60 BYTE)               NULL,
  XT_BBKZB_DBDWJLB  VARCHAR2(2000 BYTE)             NULL
);



CREATE TABLE RS_RYXX
(
  RY_DM     CHAR(11 BYTE)                       NOT NULL,
  RY_XM     VARCHAR2(30 BYTE)                   NOT NULL,
  DW_JG_DM  CHAR(15 BYTE)                       NOT NULL,
  BM_JG_DM  CHAR(15 BYTE)                       NOT NULL,
  ADDRESS   VARCHAR2(80 BYTE)                       NULL,
  ZJHM      VARCHAR2(18 BYTE)                   NOT NULL,
  DHHM      VARCHAR2(30 BYTE)                       NULL,
  SJHM      VARCHAR2(30 BYTE)                       NULL,
  EMAIL     VARCHAR2(50 BYTE)                       NULL,
  CONSTRAINT PK_RS_RYXX
 PRIMARY KEY
 (RY_DM)
);



CREATE TABLE DM_XTDMLX
(
  DMLXBH  VARCHAR2(10 BYTE)                         NULL,
  DMLXMC  VARCHAR2(30 BYTE)                         NULL,
  DMLXSM  VARCHAR2(120 BYTE)                        NULL
);

COMMENT ON TABLE DM_XTDMLX IS '系统类型代码';

COMMENT ON COLUMN DM_XTDMLX.DMLXBH IS '代码类型编号';

COMMENT ON COLUMN DM_XTDMLX.DMLXMC IS '代码类型名称';

COMMENT ON COLUMN DM_XTDMLX.DMLXSM IS '代码类型说明';



CREATE TABLE DM_XTDM
(
  DMBH  VARCHAR2(10 BYTE)                           NULL,
  DMMC  VARCHAR2(30 BYTE)                           NULL,
  DMSM  VARCHAR2(120 BYTE)                          NULL
);

COMMENT ON TABLE DM_XTDM IS '系统代码';

COMMENT ON COLUMN DM_XTDM.DMBH IS '代码编号';

COMMENT ON COLUMN DM_XTDM.DMMC IS '代码名称';

COMMENT ON COLUMN DM_XTDM.DMSM IS '代码说明';



CREATE TABLE DM_WSZL
(
  WSZL_DM  VARCHAR2(2 BYTE)                     NOT NULL,
  WSZL_MC  VARCHAR2(30 BYTE)                    NOT NULL,
  XYBZ     CHAR(1 BYTE)                         DEFAULT 'Y'                   NOT NULL,
  YXBZ     CHAR(1 BYTE)                         DEFAULT 'Y'                   NOT NULL,
  CONSTRAINT PK_DM_WSZL
 PRIMARY KEY
 (WSZL_DM)
);

COMMENT ON TABLE DM_WSZL IS '文书种类代码';

COMMENT ON COLUMN DM_WSZL.WSZL_DM IS '文书种类代码';

COMMENT ON COLUMN DM_WSZL.WSZL_MC IS '文书种类名称';

COMMENT ON COLUMN DM_WSZL.XYBZ IS '选用标志';

COMMENT ON COLUMN DM_WSZL.YXBZ IS '有效标志';



CREATE TABLE DM_DYJXH
(
  DYJXH    VARCHAR2(20 BYTE)                    NOT NULL,
  SDJG_DM  VARCHAR2(15 BYTE)                    NOT NULL,
  CONSTRAINT PK_DM_DYJXH
 PRIMARY KEY
 (DYJXH)
);

COMMENT ON COLUMN DM_DYJXH.DYJXH IS '打印机序号';

COMMENT ON COLUMN DM_DYJXH.SDJG_DM IS '设定机关代码';


CREATE TABLE DM_DYDX
(
  DYDX_DM    VARCHAR2(6 BYTE)                   NOT NULL,
  DYDX_MC    VARCHAR2(80 BYTE)                      NULL,
  WS_DM      VARCHAR2(6 BYTE)                       NULL,
  ZLZJZL_DM  VARCHAR2(4 BYTE)                       NULL,
  XYBZ       CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL,
  YXBZ       CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL,
  CONSTRAINT PK_DM_DYDX
 PRIMARY KEY
 (DYDX_DM)
);

COMMENT ON TABLE DM_DYDX IS '打印对象代码';

COMMENT ON COLUMN DM_DYDX.DYDX_DM IS '打印对象代码';

COMMENT ON COLUMN DM_DYDX.DYDX_MC IS '打印对象名称';

COMMENT ON COLUMN DM_DYDX.WS_DM IS '文书代码';

COMMENT ON COLUMN DM_DYDX.ZLZJZL_DM IS '资料证件代码';

COMMENT ON COLUMN DM_DYDX.XYBZ IS '选用标志';

COMMENT ON COLUMN DM_DYDX.YXBZ IS '有效标志';


CREATE TABLE XT_TYKJ
(
  XT_TYKJ_KJBH      VARCHAR2(30 BYTE)           NOT NULL,
  XT_TYKJ_KJMC      VARCHAR2(50 BYTE)               NULL,
  XT_TYKJ_KJLX      CHAR(1 BYTE)                    NULL,
  XT_TYKJ_KJBM      VARCHAR2(50 BYTE)               NULL,
  XT_TYKJ_KJBT      VARCHAR2(60 BYTE)               NULL,
  XT_TYKJ_CXBT      VARCHAR2(60 BYTE)               NULL,
  XT_TYKJ_CXZD      VARCHAR2(50 BYTE)               NULL,
  XT_TYKJ_BHZD      VARCHAR2(50 BYTE)               NULL,
  XT_TYKJ_BHZDBT    VARCHAR2(50 BYTE)               NULL,
  XT_TYKJ_MCZD      VARCHAR2(50 BYTE)               NULL,
  XT_TYKJ_XSZDBT    VARCHAR2(50 BYTE)               NULL,
  XT_TYKJ_QTZDLB    VARCHAR2(250 BYTE)              NULL,
  XT_TYKJ_QTZDBTLB  VARCHAR2(350 BYTE)              NULL,
  XT_TYKJ_GMC       VARCHAR2(20 BYTE)               NULL,
  XT_TYKJ_JSZD      VARCHAR2(50 BYTE)               NULL,
  XT_TYKJ_MXZD      VARCHAR2(50 BYTE)               NULL,
  XT_TYKJ_SXHZD     VARCHAR2(30 BYTE)               NULL,
  XT_TYKJ_NMZD      VARCHAR2(50 BYTE)               NULL,
  XT_TYKJ_CXTJ      VARCHAR2(250 BYTE)              NULL,
  XT_TYKJ_SFXZMX    CHAR(1 BYTE)                    NULL,
  XT_TYKJ_LXZHL     VARCHAR2(1000 BYTE)             NULL,
  XT_TYKJ_CATCH     CHAR(1 BYTE)                    NULL,
  CONSTRAINT PK_XT_TYKJ
 PRIMARY KEY
 (XT_TYKJ_KJBH)
);

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_KJMC IS '英文名称，方便调用';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_KJLX IS 'L:列表,T:树形';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_KJBM IS '所要使用到表名称';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_KJBT IS '页面显示的标题';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_CXBT IS '查询条件的标题';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_CXZD IS '查询条件的字段';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_BHZD IS '编号字段';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_QTZDLB IS '需要显示的其他字段列表';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_QTZDBTLB IS '需要显示的其他字段的标题列表';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_JSZD IS '级次字段名称';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_MXZD IS '明细字段名称';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_SXHZD IS '顺序号字段名称';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_CXTJ IS '查询条件';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_SFXZMX IS '是否选择叶子';

COMMENT ON COLUMN XT_TYKJ.XT_TYKJ_CATCH IS 'Y:需要缓存 N:不需要缓存';



CREATE TABLE DICT_CL
(
  ID    VARCHAR2(32 BYTE)                       NOT NULL,
  LB    VARCHAR2(32 BYTE)                       NOT NULL,
  CODE  VARCHAR2(32 BYTE)                       NOT NULL,
  NAME  VARCHAR2(80 BYTE)                       NOT NULL
);


CREATE TABLE DC_SYS_DICZY
(
  TABLE_ID  VARCHAR2(64 BYTE)                   NOT NULL,
  DATAID    VARCHAR2(16 BYTE)                   NOT NULL,
  DATANAME  VARCHAR2(64 BYTE)                       NULL,
  STATUS    CHAR(1 BYTE)                            NULL,
  CONSTRAINT PK_DC_SYS_DICZY
 PRIMARY KEY
 (TABLE_ID, DATAID)
);


CREATE TABLE DC_SYS_DIC
(
  TABLE_ID      VARCHAR2(64 BYTE)               NOT NULL,
  TABLE_NAME    VARCHAR2(64 BYTE)                   NULL,
  DATAID_COL    VARCHAR2(25 BYTE)                   NULL,
  DATANAME_COL  VARCHAR2(25 BYTE)                   NULL,
  GLTJ          VARCHAR2(1024 BYTE)                 NULL,
  CONSTRAINT PK_DC_SYS_DIC
 PRIMARY KEY
 (TABLE_ID)
);

COMMENT ON TABLE DC_SYS_DIC IS '系统数据字典';

COMMENT ON COLUMN DC_SYS_DIC.TABLE_ID IS '表id';

COMMENT ON COLUMN DC_SYS_DIC.TABLE_NAME IS '表名称';


CREATE UNIQUE INDEX IDX_DM_JG_JBDM ON DM_JG
(JBDM);

CREATE INDEX IDX_DM_XZQH_JCDM ON DM_XZQH
(JCDM);

CREATE INDEX IDX_DM_XZQH_JBDM ON DM_XZQH
(JBDM);

CREATE INDEX IDX_DM_XZQH_SJ ON DM_XZQH
(SJ_XZQH_DM);

CREATE INDEX IDX_QX_FAV_GNMK_USERID_ID ON QX_FAV_GNMK
(USERID);

CREATE INDEX IDX_QX_GW_EX_GW_DM ON QX_GW_EX
(GW_DM);

CREATE INDEX IDX_QX_JG_GNMK_GW_DM ON QX_JG_GNMK
(JG_DM);

CREATE INDEX IDX_QX_SYSTEM_USER_SYS ON QX_SYSTEM_USER
(SYSTEMNAME);

CREATE INDEX IDX_QX_SYSTEM_USER_USER ON QX_SYSTEM_USER
(USERID);

CREATE INDEX IDX_XT_TEMPTABLECATALOG ON XT_TEMPTABLECATALOG
(CREATINGTIME, EXPIRINGTIME);



CREATE TABLE QX_GW
(
  GW_DM     VARCHAR2(15 BYTE)                   NOT NULL,
  GW_MC     VARCHAR2(80 BYTE)                   NOT NULL,
  GWLX      VARCHAR2(2 BYTE)                        NULL,
  YWBS      VARCHAR2(5 BYTE)                        NULL,
  SJ_GW_DM  VARCHAR2(15 BYTE)                       NULL,
  QX_JG_DM  VARCHAR2(15 BYTE)                   NOT NULL,
  JG_DM     VARCHAR2(15 BYTE)                   NOT NULL,
  YWHJ_DM   VARCHAR2(6 BYTE)                    NOT NULL,
  CONSTRAINT PK_QX_GW
 PRIMARY KEY
 (GW_DM),
  CONSTRAINT FK_QX_GW_YWHJ_DM 
 FOREIGN KEY (YWHJ_DM) 
 REFERENCES DM_YWHJ (YWHJ_DM)
);

COMMENT ON COLUMN QX_GW.GW_DM IS '岗位代码';

COMMENT ON COLUMN QX_GW.GW_MC IS '岗位名称';

COMMENT ON COLUMN QX_GW.GWLX IS '岗位类型';

COMMENT ON COLUMN QX_GW.YWBS IS '业务标识';

COMMENT ON COLUMN QX_GW.SJ_GW_DM IS '上级岗位代码';

COMMENT ON COLUMN QX_GW.QX_JG_DM IS '权限机关代码';

COMMENT ON COLUMN QX_GW.JG_DM IS '机关代码';

COMMENT ON COLUMN QX_GW.YWHJ_DM IS '业务环节代码';



CREATE TABLE QX_GNMB_SX_JG
(
  GNMB_DM   VARCHAR2(11 BYTE)                   NOT NULL,
  JG_DM     VARCHAR2(15 BYTE)                   NOT NULL,
  QX_JG_DM  VARCHAR2(15 BYTE)                   NOT NULL,
  GW_DM     VARCHAR2(15 BYTE)                   NOT NULL,
  CONSTRAINT PK_QX_GNMB_SX_JG
 PRIMARY KEY
 (GNMB_DM, JG_DM),
  CONSTRAINT FK_QX_GNMB_SX_JG_GNMB_DM 
 FOREIGN KEY (GNMB_DM) 
 REFERENCES QX_GNMB (GNMB_DM)
);

COMMENT ON TABLE QX_GNMB_SX_JG IS '权限－功能模板(角色)的机关属性设置(用于根据角色批量生成岗位)';

COMMENT ON COLUMN QX_GNMB_SX_JG.GNMB_DM IS '功能模板代码';

COMMENT ON COLUMN QX_GNMB_SX_JG.JG_DM IS '机关代码';

COMMENT ON COLUMN QX_GNMB_SX_JG.QX_JG_DM IS '权限机关代码';

COMMENT ON COLUMN QX_GNMB_SX_JG.GW_DM IS '岗位代码';



CREATE TABLE QX_GNMK
(
  GNMK_DM     VARCHAR2(256 BYTE)                NOT NULL,
  GNMK_HZMC   VARCHAR2(80 BYTE)                 DEFAULT '功能模块'            NOT NULL,
  GNMK_LJMC   VARCHAR2(4000 BYTE)               NOT NULL,
  MKLX_DM     VARCHAR2(2 BYTE)                  DEFAULT '00'                  NOT NULL,
  YWHJ_DM     VARCHAR2(6 BYTE)                  NOT NULL,
  CYBJ        CHAR(1 BYTE)                          NULL,
  GZL_BZ      CHAR(1 BYTE)                          NULL,
  CFDK        CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL,
  DKWZ        CHAR(1 BYTE)                      DEFAULT '0'                   NOT NULL,
  SHOWLEFT    CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL,
  SHOWTOP     CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL,
  SHOWINTREE  CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL,
  SYSTEMNAME  VARCHAR2(80 BYTE)                 DEFAULT '系统管理'            NOT NULL,
  YXBZ        CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL,
  CONSTRAINT PK_QX_GNMK
 PRIMARY KEY
 (GNMK_DM),
  CONSTRAINT FK_QX_GNMK_SYSTEMNAME 
 FOREIGN KEY (SYSTEMNAME) 
 REFERENCES QX_SYSTEM (SYSTEMNAME),
  CONSTRAINT FK_QX_GNMK_YWHJ_DM 
 FOREIGN KEY (YWHJ_DM) 
 REFERENCES DM_YWHJ (YWHJ_DM)
);

COMMENT ON COLUMN QX_GNMK.GNMK_DM IS '功能模块代码';

COMMENT ON COLUMN QX_GNMK.GNMK_HZMC IS '功能模块汉字名称';

COMMENT ON COLUMN QX_GNMK.GNMK_LJMC IS '功能模块路径名称';

COMMENT ON COLUMN QX_GNMK.MKLX_DM IS '模块类型代码';

COMMENT ON COLUMN QX_GNMK.YWHJ_DM IS '业务环节代码';

COMMENT ON COLUMN QX_GNMK.CYBJ IS '常用标记';



CREATE TABLE DM_CZRY
(
  CZRY_DM  VARCHAR2(11 BYTE)                    NOT NULL,
  JG_DM    VARCHAR2(15 BYTE)                    NOT NULL,
  CZRY_MC  VARCHAR2(30 BYTE)                    NOT NULL,
  XYBZ     CHAR(1 BYTE)                         DEFAULT 'Y'                   NOT NULL,
  YXBZ     CHAR(1 BYTE)                         DEFAULT 'Y'                   NOT NULL,
  ZJHM     VARCHAR2(18 BYTE)                        NULL,
  ADDRESS  VARCHAR2(80 BYTE)                        NULL,
  DHHM     VARCHAR2(30 BYTE)                        NULL,
  SJHM     VARCHAR2(30 BYTE)                        NULL,
  EMAIL    VARCHAR2(50 BYTE)                        NULL,
  CONSTRAINT PK_DM_CZRY
 PRIMARY KEY
 (CZRY_DM),
  CONSTRAINT FK_DM_CZRY_JG_DM 
 FOREIGN KEY (JG_DM) 
 REFERENCES DM_JG (JG_DM)
);

COMMENT ON TABLE DM_CZRY IS '操作人员代码';

COMMENT ON COLUMN DM_CZRY.CZRY_DM IS '操作人员代码';

COMMENT ON COLUMN DM_CZRY.JG_DM IS '机构代码';

COMMENT ON COLUMN DM_CZRY.CZRY_MC IS '操作人员名称';

COMMENT ON COLUMN DM_CZRY.XYBZ IS '选用标志';

COMMENT ON COLUMN DM_CZRY.YXBZ IS '有效标志';


CREATE TABLE XT_DYYMCS
(
  DYDX_DM  VARCHAR2(6 BYTE)                     NOT NULL,
  DYJXH    VARCHAR2(20 BYTE)                    NOT NULL,
  DHDYBZ   CHAR(1 BYTE)                         NOT NULL,
  JSZHBZ   CHAR(1 BYTE)                         NOT NULL,
  MYHS     NUMBER(3)                                NULL,
  MHJG     NUMBER(5)                                NULL,
  ZZGD     NUMBER(6)                            NOT NULL,
  ZZKD     NUMBER(6)                            NOT NULL,
  PBFX     CHAR(1 BYTE)                         NOT NULL,
  CONSTRAINT PK_XT_DYYMCS
 PRIMARY KEY
 (DYDX_DM, DYJXH),
  CONSTRAINT FK_XT_DYYMCS_DYDX_DM 
 FOREIGN KEY (DYDX_DM) 
 REFERENCES DM_DYDX (DYDX_DM)
);

COMMENT ON TABLE XT_DYYMCS IS '打印页面参数';

COMMENT ON COLUMN XT_DYYMCS.DYDX_DM IS '文书代码';

COMMENT ON COLUMN XT_DYYMCS.DYJXH IS '打印机序号';

COMMENT ON COLUMN XT_DYYMCS.DHDYBZ IS '多行打印标志';

COMMENT ON COLUMN XT_DYYMCS.JSZHBZ IS '计算折行标志';

COMMENT ON COLUMN XT_DYYMCS.MYHS IS '每页行数';

COMMENT ON COLUMN XT_DYYMCS.MHJG IS '每行间隔';

COMMENT ON COLUMN XT_DYYMCS.ZZGD IS '纸张高度';

COMMENT ON COLUMN XT_DYYMCS.ZZKD IS '纸张宽度';

COMMENT ON COLUMN XT_DYYMCS.PBFX IS '排版方向';



CREATE TABLE XT_DYCS
(
  DYDX_DM  VARCHAR2(6 BYTE)                     NOT NULL,
  DYJXH    VARCHAR2(20 BYTE)                    NOT NULL,
  XMXH     VARCHAR2(3 BYTE)                     NOT NULL,
  ZHXH     VARCHAR2(3 BYTE)                     NOT NULL,
  XMMC     VARCHAR2(50 BYTE)                    NOT NULL,
  HZB      NUMBER(5)                            NOT NULL,
  ZZB      NUMBER(5)                            NOT NULL,
  DYZT     VARCHAR2(20 BYTE)                    NOT NULL,
  DYZH     NUMBER(3,1)                          NOT NULL,
  ZDZS     NUMBER(5)                            NOT NULL,
  CTBZ     CHAR(1 BYTE)                         NOT NULL,
  XTBZ     CHAR(1 BYTE)                         NOT NULL,
  XHXBZ    CHAR(1 BYTE)                         NOT NULL,
  CONSTRAINT PK_XT_DYCS
 PRIMARY KEY
 (DYDX_DM, DYJXH, XMXH, ZHXH),
  CONSTRAINT FK_XT_DYCS_DYDX_DM 
 FOREIGN KEY (DYDX_DM) 
 REFERENCES DM_DYDX (DYDX_DM)
);

COMMENT ON TABLE XT_DYCS IS '打印参数';

COMMENT ON COLUMN XT_DYCS.DYDX_DM IS '文书代码';

COMMENT ON COLUMN XT_DYCS.DYJXH IS '打印机序号';

COMMENT ON COLUMN XT_DYCS.XMXH IS '项目序号';

COMMENT ON COLUMN XT_DYCS.ZHXH IS '折行序号';

COMMENT ON COLUMN XT_DYCS.XMMC IS '项目名称';

COMMENT ON COLUMN XT_DYCS.HZB IS '横坐标';

COMMENT ON COLUMN XT_DYCS.ZZB IS '纵坐标';

COMMENT ON COLUMN XT_DYCS.DYZT IS '打印字体';

COMMENT ON COLUMN XT_DYCS.DYZH IS '打印字号';

COMMENT ON COLUMN XT_DYCS.ZDZS IS '最多字数';

COMMENT ON COLUMN XT_DYCS.CTBZ IS '粗体标志';

COMMENT ON COLUMN XT_DYCS.XTBZ IS '斜体标志';

COMMENT ON COLUMN XT_DYCS.XHXBZ IS '下划线标志';




CREATE INDEX IDX_DM_CZRY_JG_DM ON DM_CZRY
(JG_DM);




CREATE TABLE QX_GW_GNMB
(
  GW_DM    VARCHAR2(15 BYTE)                    NOT NULL,
  GNMB_DM  VARCHAR2(11 BYTE)                    NOT NULL,
  CONSTRAINT PK_QX_GW_GNMB
 PRIMARY KEY
 (GW_DM, GNMB_DM),
  CONSTRAINT FK_QX_GW_GNMB_GNMB_DM 
 FOREIGN KEY (GNMB_DM) 
 REFERENCES QX_GNMB (GNMB_DM),
  CONSTRAINT FK_QX_GW_GNMB_GW_DM 
 FOREIGN KEY (GW_DM) 
 REFERENCES QX_GW (GW_DM)
);

COMMENT ON COLUMN QX_GW_GNMB.GW_DM IS '岗位代码';

COMMENT ON COLUMN QX_GW_GNMB.GNMB_DM IS '功能模板代码';



CREATE TABLE QX_GNMB_GNMK_OPERATION
(
  GNMB_DM           VARCHAR2(11 BYTE)           NOT NULL,
  GNMK_DM           VARCHAR2(256 BYTE)          NOT NULL,
  OPERATION_DM      VARCHAR2(256 BYTE)          NOT NULL,
  OPERATIONAUTH_ID  VARCHAR2(21 BYTE)               NULL,
  CONSTRAINT PK_QX_GNMB_GNMK_OPERATION
 PRIMARY KEY
 (GNMB_DM, GNMK_DM, OPERATION_DM),
  CONSTRAINT FK_QX_GNMB_GNMK_O_GNMK_DM 
 FOREIGN KEY (GNMK_DM) 
 REFERENCES QX_GNMK (GNMK_DM)
    ON DELETE CASCADE,
  CONSTRAINT FK_QX_GNMB_GNMK_O_GNMB_DM 
 FOREIGN KEY (GNMB_DM) 
 REFERENCES QX_GNMB (GNMB_DM)
    ON DELETE CASCADE
);

COMMENT ON TABLE QX_GNMB_GNMK_OPERATION IS '权限功能模板功能模块操作';

COMMENT ON COLUMN QX_GNMB_GNMK_OPERATION.GNMB_DM IS '功能模板代码';

COMMENT ON COLUMN QX_GNMB_GNMK_OPERATION.GNMK_DM IS '功能模块代码';

COMMENT ON COLUMN QX_GNMB_GNMK_OPERATION.OPERATION_DM IS '操作代码';


CREATE TABLE QX_GNMB_GNMK
(
  GNMB_DM   VARCHAR2(11 BYTE)                   NOT NULL,
  GNMK_DM   VARCHAR2(256 BYTE)                  NOT NULL,
  JD_DM     VARCHAR2(21 BYTE)                   NOT NULL,
  FJD_DM    VARCHAR2(21 BYTE)                   NOT NULL,
  JD_MC     VARCHAR2(80 BYTE)                   NOT NULL,
  JD_ORDER  NUMBER(5)                           DEFAULT 0                     NOT NULL,
  CONSTRAINT PK_QX_GNMB_GNMK
 PRIMARY KEY
 (GNMB_DM, GNMK_DM, JD_DM, FJD_DM),
  CONSTRAINT FK_QX_GNMB_GNMK_GNMB_DM 
 FOREIGN KEY (GNMB_DM) 
 REFERENCES QX_GNMB (GNMB_DM),
  CONSTRAINT FK_QX_GNMB_GNMK_GNMK_DM 
 FOREIGN KEY (GNMK_DM) 
 REFERENCES QX_GNMK (GNMK_DM)
);

COMMENT ON COLUMN QX_GNMB_GNMK.GNMB_DM IS '功能模板代码';

COMMENT ON COLUMN QX_GNMB_GNMK.GNMK_DM IS '功能模块代码';

COMMENT ON COLUMN QX_GNMB_GNMK.JD_DM IS '节点名称';

COMMENT ON COLUMN QX_GNMB_GNMK.FJD_DM IS '节点代码';

COMMENT ON COLUMN QX_GNMB_GNMK.JD_MC IS '父节点代码';



CREATE TABLE QX_OPERATION
(
  OPERATION_DM           VARCHAR2(256 BYTE)     NOT NULL,
  OPERATION_MC           VARCHAR2(120 BYTE)     DEFAULT '操作'                NOT NULL,
  GNMK_DM                VARCHAR2(256 BYTE)     NOT NULL,
  OPERATION_DESCRIPTION  VARCHAR2(256 BYTE)         NULL,
  YXBZ                   CHAR(1 BYTE)           DEFAULT 'Y'                   NOT NULL,
  WSQCZCLFS_DM           VARCHAR2(16 BYTE)      DEFAULT '00'                  NOT NULL,
  CONSTRAINT PK_QX_OPERATION
 PRIMARY KEY
 (OPERATION_DM, GNMK_DM),
  CONSTRAINT FK_QX_OPERATION_GNMK_DM 
 FOREIGN KEY (GNMK_DM) 
 REFERENCES QX_GNMK (GNMK_DM)
    ON DELETE CASCADE
);

COMMENT ON TABLE QX_OPERATION IS '操作';

COMMENT ON COLUMN QX_OPERATION.OPERATION_DM IS '操作代码';

COMMENT ON COLUMN QX_OPERATION.OPERATION_MC IS '操作名称';

COMMENT ON COLUMN QX_OPERATION.GNMK_DM IS '功能模块代码';

COMMENT ON COLUMN QX_OPERATION.OPERATION_DESCRIPTION IS '操作描述';

COMMENT ON COLUMN QX_OPERATION.YXBZ IS '有效标志';

COMMENT ON COLUMN QX_OPERATION.WSQCZCLFS_DM IS '未授权操作处理方式代码';


CREATE TABLE QX_GNMK_TREE
(
  JD_DM     VARCHAR2(21 BYTE)                   NOT NULL,
  FJD_DM    VARCHAR2(21 BYTE)                   NOT NULL,
  JD_MC     VARCHAR2(80 BYTE)                   NOT NULL,
  GNMK_DM   VARCHAR2(256 BYTE)                      NULL,
  JDLX_DM   VARCHAR2(2 BYTE)                        NULL,
  JD_ORDER  NUMBER(5)                           NOT NULL,
  CONSTRAINT PK_QX_GNMK_TREE
 PRIMARY KEY
 (JD_DM),
  CONSTRAINT FK_QX_GNMK_TREE_GNMK_DM 
 FOREIGN KEY (GNMK_DM) 
 REFERENCES QX_GNMK (GNMK_DM)
);

COMMENT ON COLUMN QX_GNMK_TREE.JD_DM IS '功能模块代码';

COMMENT ON COLUMN QX_GNMK_TREE.FJD_DM IS '节点类型代码';

COMMENT ON COLUMN QX_GNMK_TREE.JD_MC IS '节点名称';

COMMENT ON COLUMN QX_GNMK_TREE.GNMK_DM IS '节点代码';

COMMENT ON COLUMN QX_GNMK_TREE.JDLX_DM IS '父节点代码';

COMMENT ON COLUMN QX_GNMK_TREE.JD_ORDER IS '节点顺序';



CREATE TABLE QX_USER
(
  USERID     VARCHAR2(11 BYTE)                  NOT NULL,
  NAME       VARCHAR2(30 BYTE)                  NOT NULL,
  CZRY_DM    VARCHAR2(11 BYTE)                  NOT NULL,
  PASSWORD   VARCHAR2(40 BYTE)                  NOT NULL,
  KLLX       VARCHAR2(2 BYTE)                   NOT NULL,
  PWRQQ      DATE                                   NULL,
  PWRQZ      DATE                                   NULL,
  GRANTROLE  CHAR(1 BYTE)                           NULL,
  CONSTRAINT PK_QX_USER
 PRIMARY KEY
 (USERID),
  CONSTRAINT FK_QX_USER_RY_DM 
 FOREIGN KEY (CZRY_DM) 
 REFERENCES DM_CZRY (CZRY_DM)
);

COMMENT ON TABLE QX_USER IS '用户';

COMMENT ON COLUMN QX_USER.USERID IS '用户ID';

COMMENT ON COLUMN QX_USER.NAME IS '用户名';

COMMENT ON COLUMN QX_USER.CZRY_DM IS '人员代码';

COMMENT ON COLUMN QX_USER.PASSWORD IS '口令';

COMMENT ON COLUMN QX_USER.KLLX IS '口令类型';

COMMENT ON COLUMN QX_USER.PWRQQ IS '口令起始日期';

COMMENT ON COLUMN QX_USER.PWRQZ IS '口令终止日期';

COMMENT ON COLUMN QX_USER.GRANTROLE IS '角色授权标记';


CREATE UNIQUE INDEX IDX_QX_USER_NAME ON QX_USER
(NAME);


CREATE INDEX IDX_QX_USER_RY_DM ON QX_USER
(CZRY_DM);



CREATE TABLE QX_USER_GW
(
  USERID  VARCHAR2(11 BYTE)                     NOT NULL,
  GW_DM   VARCHAR2(15 BYTE)                     NOT NULL,
  CONSTRAINT PK_QX_USER_GW
 PRIMARY KEY
 (USERID, GW_DM),
  CONSTRAINT FK_QX_USER_GW_GW_DM 
 FOREIGN KEY (GW_DM) 
 REFERENCES QX_GW (GW_DM),
  CONSTRAINT FK_QX_USER_GW_USERID 
 FOREIGN KEY (USERID) 
 REFERENCES QX_USER (USERID)
);

COMMENT ON COLUMN QX_USER_GW.USERID IS '用户ID';

COMMENT ON COLUMN QX_USER_GW.GW_DM IS '岗位代码';

