CREATE SEQUENCE HIBERNATE_SEQUENCE INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQ_WSPZXH INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999 CYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQ_PI_PHDDH INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 CYCLE CACHE 20 NOORDER;
CREATE SEQUENCE SEQ_TOPIC_ID INCREMENT BY 1 START WITH 1 MAXVALUE 99999999 CYCLE CACHE 20 NOORDER;
create sequence ESB2_TRANS_EXTEND_LOG_seq increment by 1 start with 1 nomaxvalue nominvalue nocache;