alter table BASESERVICES modify (DESCRIPTION VARCHAR2(1000));

alter table BUSSSERVICES modify (DESCRIPTION VARCHAR2(1000));

alter table DEPLOYMENTS modify (DESCRIPTION VARCHAR2(1000));

alter table DEPLOYUNITS modify (DESCRIPTION VARCHAR2(1000));

alter table ESB2_FLOW_CTRL modify (KEYWORD NVARCHAR2(500));

alter table ESB2_IN_FLOW_CTRL modify (KEYWORD NVARCHAR2(500));

alter table METADATA_MANAGER modify (DESCRIPTION VARCHAR2(1000));

alter table METADATA_TYPE modify (OPERATION VARCHAR2(1000));

alter table SERVICESYSTEM modify (DESCRIPTION VARCHAR2(1000));

alter table SERVICESYSTEMATTR modify (ATTRDESC VARCHAR2(1000));

alter table WEBSERVICES modify (DESCRIPTION VARCHAR2(1000));

alter table ESB_ADAPTER_TYPE modify (TYPEDESC VARCHAR2(1000));

alter table DATAADAPTER_PARAM modify (PARAMDESC VARCHAR2(1000));


CREATE TABLE COMB_BUSS_LOG
(
  FLOWNO         VARCHAR2(100 BYTE)         NOT NULL,
  BUSSSEQNO      VARCHAR2(100 BYTE),
  CONSUMERSEQNO  VARCHAR2(100 BYTE),
  CONSUMERID  VARCHAR2(20 BYTE),
  SERVICEID  VARCHAR2(40 BYTE),
  RESPCODE  VARCHAR2(40 BYTE),
  RESPMSG  VARCHAR2(1000 BYTE),
  STARTTIME         TIMESTAMP(3)                DEFAULT systimestamp          NOT NULL,
  ENDTTIME         TIMESTAMP(3),
  STATUS        CHAR(2 BYTE),
  LOOPID  VARCHAR2(40 BYTE)
);
alter table COMB_BUSS_LOG
  add constraint COMB_BUSS_LOG primary key (FLOWNO);


CREATE TABLE COMB_BUSS_DATA_DEF
(
  FLOWNO         VARCHAR2(100 BYTE)         NOT NULL,
  SERVICESTEPID      VARCHAR2(18 BYTE)         NOT NULL,
  CONSUMERSEQNO  VARCHAR2(100 BYTE),
  SERVICEID  VARCHAR2(40 BYTE),
  RESPCODE  VARCHAR2(40 BYTE),
  RESPMSG  VARCHAR2(1000 BYTE),
  STARTTIME         TIMESTAMP(3)                DEFAULT systimestamp          NOT NULL,
  ENDTTIME         TIMESTAMP(3),
  STATUS        CHAR(2 BYTE),
  REMARK  VARCHAR2(40 BYTE),
  REQDATA  BLOB,
  RESPDATA  BLOB
);
alter table COMB_BUSS_DATA_DEF
  add constraint COMB_BUSS_DATA_DEF primary key (FLOWNO, SERVICESTEPID);


CREATE TABLE COMB_BUSS_JOB
(
  FLOWNO         VARCHAR2(100 BYTE)         NOT NULL,
  SERVICESTEPID      VARCHAR2(18 BYTE)         NOT NULL,
  CURRNUM  INTEGER,
  LASTTIME         DATE                DEFAULT sysdate          NOT NULL,
  STATUS        CHAR(2 BYTE),
  RULEID  VARCHAR2(100 BYTE)
);
alter table COMB_BUSS_JOB
  add constraint COMB_BUSS_JOB primary key (FLOWNO, SERVICESTEPID);


CREATE TABLE COMB_BUSS_JOB_RULE
(
  RULEID  VARCHAR2(100 BYTE)         NOT NULL,
  MAXNUM  INTEGER,
  INTERVAL  INTEGER,
  PRIORITYLEVEL  INTEGER,
  RUNTASK         VARCHAR2(500 BYTE),
  FINISHTASK      VARCHAR2(500 BYTE)
);
alter table COMB_BUSS_JOB_RULE
  add constraint COMB_BUSS_JOB_RULE primary key (RULEID);

